[package]
name = "postflop-solver"
version = "0.1.0"
authors = ["Wataru Inariba"]
edition = "2021"
description = "An open-source postflop solver for Texas hold'em poker"
documentation = "https://b-inary.github.io/postflop_solver/postflop_solver/"
repository = "https://github.com/b-inary/postflop-solver"
license = "AGPL-3.0-or-later"

[lib]
name = "postflop_solver"
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = { version = "2.0.0-rc.3", optional = true }
once_cell = "1.18.0"
rayon = { version = "1.8.0", optional = true }
regex = "1.9.6"
zstd = { version = "0.12.4", optional = true, default-features = false }
pyo3 = { version = "0.19", features = ["extension-module", "abi3-py38"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["bincode", "rayon"]
custom-alloc = []
rayon = ["dep:rayon", "zstd?/zstdmt"]
python = ["dep:pyo3"]

[build-dependencies]
pkg-config = "0.3"
